config:
  token: NzYzMzkyMzU1MTcyMjIwOTI5.X33CiA.gPcKl9Vt-1CKsqqdssKayOcao_I
  game: Helping Loviti
  dm_response:
    reaction:
    - ""
    response:
    - "Im wondering why your talking to me"
    - "But Hi Human!"